#!/bin/sh
# set the version numbers in hyper.rc automatically
export VER=`grep "#define VER " hyper.cpp | sed "s/#define VER \"//" | sed "s/\"//"`
#export VERNUM=`grep "#define VERNUM " hyper.cpp | sed "s/#define VERNUM //" | sed "s/^\(.\)\(.\)\(.\)\(.\)$/\1.\2.\4.\3/"`
VERNUM=9,4,0,6
#VERNUM=8.1.7.0
#echo $VERNUM
sed "s/\"ProductVersion\", \"\(.*\)\"/\"ProductVersion\", \"$VER\"/" -i hyper.rc
sed "s/FILEVERSION   \(.*\)$/FILEVERSION     $VERNUM/" -i hyper.rc
sed "s/PRODUCTVERSION\(.*\)$/PRODUCTVERSION  $VERNUM/" -i hyper.rc
# Adjust it in configure.ac
sed "s/AC_INIT.*/AC_INIT([hyperrogue], [$VER])/" -i configure.ac
echo $VER
