// include all RogueViz vizualizations

#include "rogueviz.cpp"
#include "kohonen.cpp"
#include "staircase.cpp"
#include "banachtarski.cpp"
#include "pentagonal.cpp"
#include "functions.cpp"
#include "fundamental.cpp"
#include "sunflower.cpp"
#include "flocking.cpp"
#include "magiccube.cpp"
#include "cvl.cpp"
#include "newconf.cpp"
#include "grigorchuk.cpp"
#include "janko.cpp"
#include "qtm.cpp"
#include "rewriting.cpp"
#include "sag.cpp"
#include "collatz.cpp"
#include "tree.cpp"
#include "fullnet.cpp"
#include "snow.cpp"
#include "impossible-ring.cpp"
#include "triangle.cpp"
#include "sumotron.cpp"
#include "noniso-honeycombs.cpp"
#include "random-walk.cpp"
